default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Minimal_CRUD_Hotwire_development

test:
  <<: *default
  database: Minimal_CRUD_Hotwire_test

production:
  <<: *default
  database: Minimal_CRUD_Hotwire_production
  username: Minimal_CRUD_Hotwire
  password: <%= ENV["MINIMAL_CRUD_HOTWIRE_DATABASE_PASSWORD"] %>
